# Site settings
title:        "Alireza Mirsepassi"
description:  "This is Alireza Mirsepassi's personal CV page."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Alireza Mirsepassi"
resume_title:                   "Full Stack Web Developer"
resume_contact_email:           "lord@alireza.rocks"
resume_contact_telephone:       "+989106622764"
resume_contact_address:         "Tehran, Iran"
resume_header_contact_info:     "Tehran, Iran | +989106622764 | lord@alireza.rocks"
resume_header_intro:            "<p>My name is Alireza Mirsepassi. I was born in Iran and since then I have lived in Iran. I am sort of young developers whose goal is to learn more and more about the new things. The more I work in this field, the more I feel I must work harder to gain exprience.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
# resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/alirezamirsepassi"
  resume_twitter_url:           "http://twitter.com/alirezamirsepassi"
  resume_telegram_url:          "https://t.me/thefallingangel"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/alirezamirsepassy/"
  resume_instagram_url:         "https://instagram.com/alirezamirsepassi"
  resume_website_url:           "https://alireza.rocks"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
